version: 0.2

environment_variables:
  plaintext:
    DOCKER_REPOSITORY_NAME: env-authorization-repository
    AUTHORIZATION_ENGINE_CONTAINER: env-authorization-engine
    SAM_CLI_TELEMETRY: 0

phases:
  build:
    commands:
      # Create respository
      - aws ecr create-repository --repository-name ${DOCKER_REPOSITORY_NAME} || true --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=true
      # Sign in to ECR
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      # Build docker image
      - docker build -t ${AUTHORIZATION_ENGINE_CONTAINER} .
      # Tag the image
      - docker tag ${AUTHORIZATION_ENGINE_CONTAINER}:latest ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${DOCKER_REPOSITORY_NAME}:${AUTHORIZATION_ENGINE_CONTAINER}
      # Push the image to the registry
      - docker push ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${DOCKER_REPOSITORY_NAME}:${AUTHORIZATION_ENGINE_CONTAINER}
