version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 751354400372.dkr.ecr.eu-west-1.amazonaws.com
      - docker build -t env-authorization-service .
      - docker tag env-authorization-service:latest 751354400372.dkr.ecr.eu-west-1.amazonaws.com/env-authorization-service:latest
      - docker push 751354400372.dkr.ecr.eu-west-1.amazonaws.com/env-authorization-service:latest
