# The maximum allowed number of tuples per Write transaction.
maxTuplesPerWrite: 100

# The maximum allowed number of type definitions per authorization model.
maxTypesPerAuthorizationModel: 100

# The offset (in minutes) from the current time. Changes that occur after this offset will not be included in the response of ReadChanges.
changelogHorizonOffset: 0

# Defines how deeply nested an authorization model can be.
resolveNodeLimit: 25

# The timeout deadline for serving ListObjects requests
listObjectsDeadline: 3s

# The maximum results to return in ListObjects responses
listObjectsMaxResults: 1000

playground:
  # Enable/disable the OpenFGA Playground.
  enabled: true
  # The port to serve the local OpenFGA Playground on.
  port: 3000

profiler:
  # Enabled/disable pprof profiling.
  enabled: false
  # The host:port address to serve the pprof profiler server on.
  addr: :3001

# datastore:
#   # The datastore engine that will be used for persistence.
#   engine: postgres
#   # The connection uri to use to connect to the datastore (for any engine other than 'memory').
#   uri: postgres://user:password@localhost:5432/mydatabase
#   # The maximum number of cache keys that the storage cache can store before evicting old keys.
#   maxCacheSize: 100000

# authn:
#   # The authentication method to use.
#   method: oidc
#   # The OIDC provider specific settings. This must be set if 'authn.method=oidc'.
#   oidc:
#     # The OIDC issuer (authorization server) signing the tokens.
#     issuer: https://accounts.google.com
#     # The OIDC audience of the tokens being signed by the authorization server.
#     audience: 1234567890-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com

grpc:
  # Enables or disables the OpenFGA grpc server. If 'http.enabled' is set to true, then this must be set to true.
  enabled: true
  # The host:port address to serve the grpc server on.
  addr: :8081
  tls:
    # Enables or disables transport layer security (TLS).
    enabled: false
    # The (absolute) file path of the certificate to use for the TLS connection.
    cert: ""
    # The (absolute) file path of the TLS key that should be used for the TLS connection.
    key: ""

http:
  # Enables or disables the OpenFGA HTTP server. If this is set to true then 'grpc.enabled' must be set to true.
  enabled: true
  # The host:port address to serve the HTTP server on.
  addr: :8080
  tls:
    # Enables or disables transport layer security (TLS).
    enabled: false
    # The (absolute) file path of the certificate to use for the TLS connection.
    cert: ""
    # The (absolute) file path of the TLS key that should be used for the TLS connection.
    key: ""
  # The timeout duration for proxying HTTP requests upstream to the grpc endpoint.
  upstreamTimeout: 3s
  # Allowed orgins for CORS requests.
  corsAllowedOrigins:
    - "*"
  # Allowed methods for CORS requests.
  corsAllowedHeaders:
    - "*"
log:
  # The log format to output logs in. For production we recommend 'json' format.
  format: json
