name: Deploy to AWS
on:
  push:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

env:
  DOMAIN: "env-authorization-engine"
  OWNER: "env-authorization"
  TEAM: "dev-pricing"
  ACCOUNTNAME:
  AWS_DEPLOY_REGION: "eu-west-1"

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.tags.outputs.domain }}
      owner: ${{ steps.tags.outputs.owner }}
      team: ${{ steps.tags.outputs.team }}
      AWS_DEPLOY_REGION: ${{ steps.environment-variables.outputs.AWS_DEPLOY_REGION }}
      ACCOUNTNAME: ${{ steps.environment-variables.outputs.ACCOUNTNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: tags
        name: Check tags
        run: |
          echo "::set-output name=domain::$(cat ./parameters.test.json | jq -r .Tags.domain)"
          echo "::set-output name=owner::$(cat ./parameters.test.json | jq -r .Tags.owner)"
          echo "::set-output name=team::$(cat ./parameters.test.json | jq -r .Tags.team)"
      - id: environment-variables
        name: Build environment variable
        run: |
          echo "::set-output name=AWS_DEPLOY_REGION::${{ env.AWS_DEPLOY_REGION }}"
          echo "::set-output name=ACCOUNTNAME::${{ env.ACCOUNTNAME }}"

  Account:
    needs: [Setup]
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: "github-actions-oidc-session"
    secrets:
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [Setup, Account]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo configuration
        run: |
          echo "Config below"
          echo "-----------------------------------------"
          echo "Branch:           ${{ github.ref_name }}"
          echo "Domain:           ${{ needs.Setup.outputs.domain }}"
          echo "Owner:            ${{ needs.Setup.outputs.owner }}"
          echo "Team:             ${{ needs.Setup.outputs.team }}"
          echo "-----------------------------------------"
          echo "AWS region:       ${{ env.AWS_DEPLOY_REGION }}"
          echo "AWS account:      ${{ needs.Account.outputs.account }}"

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          DOMAIN: ${{ needs.Setup.outputs.domain }}
          OWNER: ${{ needs.Setup.outputs.owner }}
          TEAM: ${{ needs.Setup.outputs.team }}
          AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
          AWS_DEPLOY_REGION: ${{ env.AWS_DEPLOY_REGION }}
          AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
