name: Deploy to AWS
on:
  push:
    branches: [main, develop]

permissions:
  id-token: write
  contents: read

env:
  DOMAIN: "env-authorization-engine"
  TEAM: "dev-pricing"
  AWS_DEPLOY_REGION: "eu-west-1"

jobs:
  Setup:
    runs-on: ubuntu-latest
    outputs:
      domain: ${{ steps.env-vars.outputs.DOMAIN }}
      team: ${{ steps.env-vars.outputs.TEAM }}
      AWS_DEPLOY_REGION: ${{ steps.env-vars.outputs.AWS_DEPLOY_REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: env-vars
        name: Build environment variable
        run: |
          echo "::set-output name=DOMAIN::${{ env.DOMAIN }}"
          echo "::set-output name=TEAM::${{ env.TEAM }}"
          echo "::set-output name=TEAM::${{ env.AWS_DEPLOY_REGION }}"

  Account:
    uses: mathem-se/gh-account-mapping/.github/workflows/workflow.yml@main
    with:
      branch: ${{ github.ref_name }}
      role-session-name: "github-actions-oidc-session"
    secrets:
      AWS_REGION: ${{ secrets.AWS_CICD_API_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_CICD_ACCOUNT }}
      AWS_API: ${{ secrets.AWS_CICD_API_URL }}

  Registry:
    needs: [Setup, Account]
    runs-on: ubuntu-latest
    steps:
      - name: Create Docker repository
        shell: bash
        run: aws ecr create-repository --repository-name ${{ github.event.repository.name }} || true --image-tag-mutability IMMUTABLE --image-scanning-configuration scanOnPush=true
      - name: Docker login
        shell: bash
        run: aws ecr get-login-password --region ${{ needs.Setup.outputs.AWS_DEPLOY_REGION }} | docker login --username AWS --password-stdin ${{ needs.Account.outputs.account }}.dkr.ecr.${{ needs.Setup.outputs.AWS_DEPLOY_REGION }}.amazonaws.com
      - name: Docker build
        shell: bash
        run: docker build -t ${{ github.event.repository.name }}-container .
      - name: Tag docker container
        shell: bash
        run: docker tag ${{ github.event.repository.name }}-container:latest  ${{ needs.Account.outputs.account }}.dkr.ecr.${{ needs.Setup.outputs.AWS_DEPLOY_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ github.event.repository.name }}-container
      - name: Push container to ECR Repository
        shell: bash
        run: docker push ${{ needs.Account.outputs.account }}.dkr.ecr.${{ enneeds.Setup.outputs.AWS_DEPLOY_REGION }}.amazonaws.com/${{ github.event.repository.name }}:${{ github.event.repository.name }}-container

  Deploy:
    needs: [Setup, Account, Registry]
    uses: mathem-se/ecom-gh-actions/.github/workflows/deploy.yml@main
    with:
      environment: ${{ needs.Account.outputs.environment}}
      domain: ${{ needs.Setup.outputs.DOMAIN }}
      team: ${{ needs.Setup.outputs.TEAM }}
      AWS_DEPLOY_REGION: ${{ needs.Setup.outputs.AWS_DEPLOY_REGION }}
    secrets:
      AWS_ACCOUNT: ${{ needs.Account.outputs.account }}
      AWS_API_REGION: ${{ secrets.AWS_CICD_API_REGION }}
